### ISSUE TITLE
content lists bug

### ISSUE THREAD

**Issue by mehdignu** [superdesk/superdesk-publisher#200]
i have superdesk / web-publisher 2.0, when i want to create a new new automatic list i get the following bug

![Superdesk_-_Dashboard_and_Slack___Verena_Märtens___Funke_Digital_GmbH](https://user-images.githubusercontent.com/5521531/66910711-5e5f7280-f00f-11e9-8c49-01cfe8b6c404.png)

**Comment by ahilles107** [comment]
Resolved in #201

**Comment by tomaszrondio** [comment]
https://github.com/superdesk/superdesk-publisher/pull/203
