### ISSUE TITLE
Publisher - Output Settings - Add Site - 404 error

### ISSUE THREAD

**Issue by jvkiran** [superdesk/superdesk-publisher#28]
Hello,
Trying to add site and theme, but issue.

**Request Url:** http://localhost:5000/api/v1/tenants/
**params:**
tenant: {
      domainName: xsaxsaxsa
      name: xsxsa 
}
**Response error:** The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again

Stuck at this step, please help.

**Comment by takeit** [comment]
Hi @jvkiran,

are you sure the url you are calling is correct? Looks like it's not a valid Superdesk Publisher API endpoint. It should point to the Superdesk Publisher API and now it looks like it's calling Superdesk instance.

See https://medium.com/@takeit/how-to-install-and-configure-superdesk-and-superdesk-publisher-bb761da36eee on how to install Superdesk together with Superdesk Publisher.

**Comment by jvkiran** [comment]
Thanks @takeit, it's solved.
