### ISSUE TITLE
"Publish" button is disabled even when initial state is valid

### ISSUE THREAD

**Issue by kottkrig** [superdesk/superdesk-publisher#330]
## Current behaviour

In output control, when an article have an automatically set route (based on suggestion from rules), the "Publish" button is disabled.

<img width="200" alt="Skärmavbild 2022-01-20 kl  11 58 09" src="https://user-images.githubusercontent.com/52966/150326017-7c8ddaed-f5e0-4f96-aa23-fdbe18cc115d.png">

It reenables when changing route. It also stays enabled when changing to the original route.

<img width="200" alt="Skärmavbild 2022-01-20 kl  11 58 21" src="https://user-images.githubusercontent.com/52966/150326058-59c2f38c-bd62-437c-a325-d5ecc15cae22.png">

## Expected behaviour

The initial state of the button should be enabled when the route is set.

## Possible fix/solution

There seems to be a problem with the initial state of the PublishPane where the button is only enabled in response to a change to the dropdown.

Perhaps an issue with this helper? 

https://github.com/superdesk/superdesk-publisher/blob/647b1555ca020ef8f0acaf0c6710cd52ed77e336/client/components/Output/PublishPane/Publish.jsx#L181-L184

**Comment by tomaszrondio** [comment]
I think this should solve the problem. https://github.com/superdesk/superdesk-publisher/pull/332

**Comment by kottkrig** [comment]
@tomaszrondio thank you! I can confirm that #332 fixed this issue.
