### ISSUE TITLE
FilterPanel is missing specific state for "priority" and "urgency"

### ISSUE THREAD

**Issue by kottkrig** [superdesk/superdesk-publisher#333]
## Current behaviour

When adding a filter to an Automatic content list for `"priority"` or `"urgency"`. The following payload is generated and sent to Publisher API. Publisher API will respond with "500 internal error".

```
{
"filters": "{"metadata":{"subject":[{"scheme":"priority","code":6}]}}"
}
```

<img width="200" alt="Skärmavbild 2022-01-21 kl  16 38 11" src="https://user-images.githubusercontent.com/52966/150555381-8fe5dfdf-1941-4710-967f-f6cb350c0d73.png">

## Expected behaviour

`"priority"` and `"urgency"` should not be nested inside of the `"subject"` array. Instead, they should be moved to the `"metadata"` dictionary. Expected payload should look like this:

```
{
"filters": "{"metadata":{"priority":6}}"
}
```

**Comment by tomaszrondio** [comment]
@kottkrig this should solve the issue. https://github.com/superdesk/superdesk-publisher/pull/336
