### ISSUE TITLE
Permission denied in www-data

### ISSUE THREAD

**Issue by thehatami** [superdesk/superdesk-publisher#51]
i get permission error in `sudo -u www-data SYMFONY_ENV=prod php app/console rabbitmq-supervisor:build --env=prod` as below:

`PHP Warning:  unlink(/var/www/publisher/var/supervisor/prod/worker/analytics_event.conf): Permission denied in /var/www/publisher/vendor/phobetor/rabbitmq-supervisor-bundle/Phobetor/RabbitMqSupervisorBundle/Services/RabbitMqSupervisor.php on line 121
PHP Warning:  unlink(/var/www/publisher/var/supervisor/prod/worker/send_webhook.conf): Permission denied in /var/www/publisher/vendor/phobetor/rabbitmq-supervisor-bundle/Phobetor/RabbitMqSupervisorBundle/Services/RabbitMqSupervisor.php on line 121
PHP Warning:  file_put_contents(/var/www/publisher/var/supervisor/prod/worker/send_webhook.conf): failed to open stream: Permission denied in /var/www/publisher/vendor/phobetor/rabbitmq-supervisor-bundle/Phobetor/RabbitMqSupervisorBundle/Services/RabbitMqSupervisor.php on line 471
PHP Warning:  file_put_contents(/var/www/publisher/var/supervisor/prod/worker/analytics_event.conf): failed to open stream: Permission denied in /var/www/publisher/vendor/phobetor/rabbitmq-supervisor-bundle/Phobetor/RabbitMqSupervisorBundle/Services/RabbitMqSupervisor.php on line 471`

but not get error if i replace `www-data` with `root`. how can i fix it?

**Comment by ahilles107** [comment]
This repo is for client ui. Please open Your issue here: https://github.com/superdesk/web-publisher/issues. And make sure that you use latests released version and follow installation notes.
